version: 2
updates:
  - package-ecosystem: pip
    commit-message:
      prefix: "chore"
    directory: /packaging/cfengine-nova-hub/
    schedule:
      interval: "weekly"
      day: "monday"
      time: "15:40"
      timezone: "Europe/Berlin"
