version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /packaging/cfengine-nova-hub/
    package-ecosystem: pip
    schedule:
      interval: "weekly"
      day: "monday"
      time: "15:08"
      timezone: "Europe/Berlin"
