version: 2
updates:
  - package-ecosystem: gitsubmodule
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "15:14"
      timezone: "Europe/Berlin"
