version: 2
updates:
  - package-ecosystem: gitsubmodule
    commit-message:
      prefix: "chore"
    directory: /repo-two
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "15:12"
      timezone: "Europe/Berlin"
