version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: pip
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:50"
      timezone: "Europe/Berlin"
