name: Build and Deploy Two Mender Artifacts

on:
  push:
    branches:
      - main

env:
  MENDER_DEPLOYMENT_DEVICES_GROUP_PREFIX: group-dev
  MENDER_SERVER_URL: https://hosted.mender.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: ["sensor", "executive"]
    container:
      image: mendersoftware/mender-ci-tools:men-5906_build_and_publish_mender-ci-tools_image_5b8f51afb7ffab3ea7d3d433bcd5115463ae08fa
    steps:
      - uses: actions/checkout@v2
      - name: Generrate Mender Release Name
        run: |
          APP_NAME=change-the-world-to-better
          VERSION="$(($RANDOM%9+1)).$(($RANDOM%9+1)).$(($RANDOM%9+1))"
          MENDER_RELEASE_NAME=${APP_NAME}_v${VERSION}
          echo "MENDER_RELEASE_NAME=${MENDER_RELEASE_NAME}" >> ${GITHUB_ENV}
      - name: Generate Mender Deployment Name
        run: |
          COMMIT_SHORT_SHA="${GITHUB_SHA:0:8}"
          MENDER_DEPLOYMENT_NAME=${{ matrix.device }}_${MENDER_RELEASE_NAME}_${COMMIT_SHORT_SHA}
          echo "MENDER_DEPLOYMENT_NAME=${MENDER_DEPLOYMENT_NAME}" >> ${GITHUB_ENV}
      - name: Create Mender Artifact
        run: |
          MENDER_ARTIFACT_NAME=artifact_$(( $RANDOM % 9999 + 1000 )).mender
          echo /home/root/.ssh > dest_dir
          echo authorized_keys > filename
          echo key > authorized_keys
          SOFTWARE_NAME=${{ matrix.device }}
          SOFTWARE_VERSION="$(($RANDOM%9+1)).$(($RANDOM%9+1))"
          mender-artifact write module-image \
            -T single-file \
            --device-type raspberrypi4 \
            -o ${MENDER_ARTIFACT_NAME} \
            -n ${MENDER_RELEASE_NAME} \
            --software-name ${SOFTWARE_NAME} \
            --software-version ${SOFTWARE_VERSION} \
            -f dest_dir \
            -f filename \
            -f authorized_keys
          echo "MENDER_ARTIFACT_NAME=${MENDER_ARTIFACT_NAME}" >> ${GITHUB_ENV}
      - name: Upload Mender Artifacts to Server
        uses: 0lmi/mender-push-artifact@main
        with:
          mender_pat: ${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}
          mender_artifact: ${{ env.MENDER_ARTIFACT_NAME }}
          mender_uri: ${{ env.MENDER_SERVER_URL }}
      - name: Create Deployment on Mender Server
        uses: 0lmi/mender-create-deployment@main
        with:
          mender_pat: ${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}
          mender_uri: ${{ env.MENDER_SERVER_URL }}
          mender_deployment_name: ${{ env.MENDER_DEPLOYMENT_NAME }}
          mender_release_name: ${{ env.MENDER_RELEASE_NAME }}
          mender_devices_group: ${{ env.MENDER_DEPLOYMENT_DEVICES_GROUP_PREFIX }}-${{ matrix.device }}

