name: Call a reusable workflow

on:
  push:
    branches: [ main ]


env:
  MENDER_ARTIFACTS_CI_ARTIFACT_NAME: mender-artifacts
  MENDER_ARTIFACTS_CI_ARTIFACT_PATH: mender-artifacts
  MENDER_SERVER_URL: https://hosted.mender.io

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mendersoftware/mender-ci-tools:men-5906_build_and_publish_mender-ci-tools_image_e018e952a4e9a71c318bf2a56651293efff5d8b5
    steps:
      - uses: actions/checkout@v2      
      - name: Create Mender Artifact
        run: |
          [ ! -d ${MENDER_ARTIFACTS_PATH} ] && mkdir -p ${MENDER_ARTIFACTS_PATH}
          echo /home/root/.ssh > dest_dir
          echo authorized_keys > filename
          echo key > authorized_keys
          mender-artifact write module-image \
            -T single-file \
            --device-type raspberrypi4 \
            -o ${MENDER_ARTIFACTS_PATH}/artifact.mender \
            -n updated-authorized_keys-1.0 \
            --software-name authorized_keys \
            --software-version 1.0 \
            -f dest_dir \
            -f filename \
            -f authorized_keys
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MENDER_ARTIFACTS_CI_ARTIFACT_NAME }}
          path: ${{ env.MENDER_ARTIFACTS_CI_ARTIFACT_PATH }}

  publish:
    needs: ["build"]
    uses: 0lmi/olmi-test-repo-one/.github/workflows/publish-mender-artifact.yml@main
    with:
      MENDER_SERVER_URL: https://hosted.mender.io
      MENDER_ARTIFACTS_CI_ARTIFACT_PATH: mender-artifacts
      MENDER_ARTIFACTS_CI_ARTIFACT_NAME: mender-artifacts
    secrets: inherit
