name: Build and Deploy to a Single Device

on:
  push:
    branches:
      - production

env:
  MENDER_ARTIFACTS_CI_ARTIFACT_PATH: mender-artifast
  MENDER_DEPLOYMENT_DEVICES_GROUP_PREFIX: grp-1
  MENDER_SERVER_URL: https://hosted.mender.io
  MENDER_DEPLOYMENT_NAME: my-app-v1.0-dev
  MENDER_RELEASE_NAME: change-the-world-to-better-v1.0
  MENDER_ARTIFACT_NAME: artifact.mender
  MENDER_DEVICES_LIST: '[\"5ca6090ff3a8e90001206535\"]'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mendersoftware/mender-ci-tools:men-5906_build_and_publish_mender-ci-tools_image_5b8f51afb7ffab3ea7d3d433bcd5115463ae08fa
    steps:
      - uses: actions/checkout@v2
      - name: Create Mender Artifact
        run: |
          [ ! -d ${MENDER_ARTIFACTS_CI_ARTIFACT_PATH} ] && mkdir -p ${MENDER_ARTIFACTS_CI_ARTIFACT_PATH}
          echo /home/root/.ssh > dest_dir
          echo authorized_keys > filename
          echo key > authorized_keys
          mender-artifact write module-image \
            -T single-file \
            --device-type raspberrypi4 \
            -o ${MENDER_ARTIFACTS_CI_ARTIFACT_PATH}/${MENDER_ARTIFACT_NAME} \
            -n ${MENDER_RELEASE_NAME} \
            --software-name authorized_keys \
            --software-version 1.0 \
            -f dest_dir \
            -f filename \
            -f authorized_keys
      - name: Upload Mender Artifacts to Server
        uses: 0lmi/mender-push-artifact@main
        with:
          mender_pat: ${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}
          mender_artifact: ${{ env.MENDER_ARTIFACTS_CI_ARTIFACT_PATH }}/${{ env.MENDER_ARTIFACT_NAME }}
          mender_uri: ${{ env.MENDER_SERVER_URL }}
      - name: Create Deployment on Mender Server
        uses: 0lmi/mender-create-deployment@main
        with:
          mender_pat: ${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}
          mender_uri: ${{ env.MENDER_SERVER_URL }}
          mender_deployment_name: ${{ env.MENDER_DEPLOYMENT_NAME }}
          mender_release_name: ${{ env.MENDER_RELEASE_NAME }}
          mender_devices_list: ${{ env.MENDER_DEVICES_LIST }}

