name: Build and upload Mender Artifact

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
  


jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload a dummy Mender artifact
    steps:
      - name: Env
        run: env
