name: Test Releases

on:
  push:
    branches:
      - main

env:
  VERSION: 1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download latest version
        shell: bash
        run: cat packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in | bash

      - name: Unarchive
        shell: bash
        run: find . -name ${VERSION}.tar.gz

      - name: List files
        shell: bash
        run: ls -la
