name: Build and upload Mender Artifact

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]


jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload a dummy Mender artifact
    steps:
      - name: Prepare Dockerfile
        run: |
          cat > Dockerfile-schema-tests << EOF
            FROM ubuntu:22.04
            RUN apt-get update apt-get install -y systemd sudo prove6 wget git
            CMD [ "/lib/systemd/systemd" ]
          EOF
      - name: Cat
        run: cat Dockerfile-schema-tests
