name: Build and upload Mender Artifact

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]


jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload a dummy Mender artifact
    steps:
      - name: Env
        env:
          MY_HOME_ONE: $HOME
          MY_HOME_TWO: ${HOME}
          MY_HOME_FOUR: ${{ env.HOME }}
          MY_HOME_FIVE: ${{ vars.HOME }}
        run: |
          echo "HOME=$HOME"
          echo "MY_HOME_ONE=$MY_HOME_ONE"
          echo "MY_HOME_TWO=$MY_HOME_TWO"
          echo "MY_HOME_FOUR=$MY_HOME_FOUR"
          echo "MY_HOME_FIVE=$MY_HOME_FIVE"
